
server:
  port: 8766


#Application name
spring:
  application:
    name: micro-service2

# Discovery Server Access
eureka:
  client:
    service-url:
      defaultZone: http://localost:8761/eureka/,http://localhost:8862/eureka/